---
- name: install base packages
  ansible.builtin.apt:
    name: "{{ base_packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: configure journald max use
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: "^#?SystemMaxUse="
    line: "SystemMaxUse={{ journald_max_use }}"
  notify: restart journald

- name: template system motd
  ansible.builtin.template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: "0644"
