---
- name: template mongodb backup runner script
  ansible.builtin.template:
    src: mongo-backup-s3.j2
    dest: /usr/local/bin/mongo-backup-s3
    owner: root
    group: root
    mode: "0755"

- name: template mongodb backup systemd units
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - mongo-backup.service
    - mongo-backup.timer

- name: enable and start mongodb backup timer
  ansible.builtin.systemd:
    name: mongo-backup.timer
    enabled: true
    state: started
    daemon_reload: true
