---
- name: install wal-g binary
  ansible.builtin.get_url:
    url: "https://github.com/wal-g/wal-g/releases/download/{{ walg_version }}/wal-g-pg-ubuntu-22.04-amd64"
    dest: /usr/local/bin/wal-g
    mode: "0755"

- name: create wal-g directory
  ansible.builtin.file:
    path: /etc/wal-g
    state: directory
    owner: postgres
    group: postgres
    mode: "0750"

- name: template wal-g configuration
  ansible.builtin.template:
    src: wal-g.json.j2
    dest: "{{ walg_config_path }}"
    owner: postgres
    group: postgres
    mode: "0600"

- name: template backup units
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    mode: "0644"
  loop:
    - walg-backup.service
    - walg-backup.timer

- name: enable backup timer
  ansible.builtin.systemd:
    name: walg-backup.timer
    enabled: true
    state: started
    daemon_reload: true
