---
- name: restart victoriametrics
  ansible.builtin.systemd:
    name: victoria-metrics
    state: restarted
    daemon_reload: true

- name: restart victorialogs
  ansible.builtin.systemd:
    name: victoria-logs
    state: restarted
    daemon_reload: true

- name: restart grafana
  ansible.builtin.systemd:
    name: grafana-server
    state: restarted
