---
- name: download redpanda gpg key
  ansible.builtin.get_url:
    url: https://packages.redpanda.com/public/redpanda/gpg.key
    dest: /tmp/redpanda.key
    mode: "0644"

- name: dearmor redpanda gpg key
  ansible.builtin.command:
    cmd: gpg --dearmor -o /etc/apt/keyrings/redpanda.gpg /tmp/redpanda.key
    creates: /etc/apt/keyrings/redpanda.gpg

- name: add redpanda apt repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [signed-by=/etc/apt/keyrings/redpanda.gpg]
      https://packages.redpanda.com/public/redpanda/deb/ubuntu
      {{ ansible_distribution_release }} main
    state: present
    filename: redpanda

- name: install redpanda packages
  ansible.builtin.apt:
    name:
      - redpanda
      - redpanda-console
    state: present
    update_cache: true

- name: enable and start redpanda service
  ansible.builtin.systemd:
    name: redpanda
    state: started
    enabled: true
