---
- name: ensure apt repository for amnezia
  ansible.builtin.apt_repository:
    repo: ppa:amnezia/ppa
    state: present
    update_cache: true
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: install amnezia wireguard packages
  ansible.builtin.apt:
    name:
      - amneziawg
      - amneziawg-tools
    state: present

- name: create amnezia config directory
  ansible.builtin.file:
    path: /etc/amnezia/amneziawg
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: template awg interface configuration
  ansible.builtin.template:
    src: awg0.conf.j2
    dest: "/etc/amnezia/amneziawg/{{ awg_iface }}.conf"
    owner: root
    group: root
    mode: "0600"
  notify: restart awg

- name: enable and start awg service
  ansible.builtin.systemd:
    name: "awg-quick@{{ awg_iface }}"
    state: started
    enabled: true
