---
- name: setup common backup infrastructure and runner
  hosts: mesh
  become: true
  roles:
    - backup_common

- name: configure backups for postgresql and platform core database
  hosts: mesh[0]
  become: true
  roles:
    - walg
    - backup_platform_db

- name: configure backups for clickhouse
  hosts: mesh
  become: true
  roles:
    - backup_clickhouse

- name: configure backups for mongodb
  hosts: mesh
  become: true
  roles:
    - backup_mongo
