---
- name: clean and prepare virtual machine for baking
  hosts: target
  become: true
  tasks:
    - name: remove ssh host keys
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/ssh/ssh_host_rsa_key
        - /etc/ssh/ssh_host_rsa_key.pub
        - /etc/ssh/ssh_host_ecdsa_key
        - /etc/ssh/ssh_host_ecdsa_key.pub
        - /etc/ssh/ssh_host_ed25519_key
        - /etc/ssh/ssh_host_ed25519_key.pub

    - name: clean machine id
      ansible.builtin.copy:
        dest: /etc/machine-id
        content: ""
        mode: "0444"

    - name: clean cloud init logs
      ansible.builtin.command:
        cmd: "cloud-init clean --logs"
      failed_when: false

    - name: trim filesystem
      ansible.builtin.command:
        cmd: "fstrim -av"
      failed_when: false
