[mesh]
node1 ansible_host=185.0.0.1 mesh_ip=10.42.0.1
node2 ansible_host=95.0.0.2 mesh_ip=10.42.0.2
node3 ansible_host=none mesh_ip=10.42.0.3

[k3s_servers]
node1
node2
node3

[all:vars]
ansible_user=root
