---
- name: restore clickhouse from s3 backup
  hosts: "{{ target_host | default('all') }}"
  become: true
  tasks:
    - name: download remote clickhouse backup from s3
      ansible.builtin.command:
        cmd: "/usr/local/bin/clickhouse-backup download {{ backup_name }}"

    - name: restore clickhouse schema
      ansible.builtin.command:
        cmd: "/usr/local/bin/clickhouse-backup restore --schema {{ backup_name }}"

    - name: restore clickhouse data
      ansible.builtin.command:
        cmd: "/usr/local/bin/clickhouse-backup restore --data {{ backup_name }}"

    - name: delete local clickhouse backup copy
      ansible.builtin.command:
        cmd: "/usr/local/bin/clickhouse-backup delete local {{ backup_name }}"
