---
- name: restore garage metadata from s3 backup
  hosts: "{{ target_host | default('all') }}"
  become: true
  vars:
    tmp_dir: "/tmp/restore_garage_{{ ansible_date_time.epoch }}"
  tasks:
    - name: create temporary directory
      ansible.builtin.file:
        path: "{{ tmp_dir }}"
        state: directory
        mode: "0750"

    - name: download garage archive from s3
      ansible.builtin.command:
        cmd: "/usr/local/bin/infra-s3-client download {{ s3_archive_key }} {{ tmp_dir }}/garage.tar.zst"

    - name: unarchive garage metadata
      ansible.builtin.shell:
        cmd: "tar -I zstd -xf {{ tmp_dir }}/garage.tar.zst -C {{ tmp_dir }}"

    - name: clean up temporary directory
      ansible.builtin.file:
        path: "{{ tmp_dir }}"
        state: absent
