---
- name: template redpanda backup runner script
  ansible.builtin.template:
    src: redpanda-backup-s3.j2
    dest: /usr/local/bin/redpanda-backup-s3
    owner: root
    group: root
    mode: "0755"

- name: template redpanda backup systemd units
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - redpanda-backup.service
    - redpanda-backup.timer

- name: enable and start redpanda backup timer
  ansible.builtin.systemd:
    name: redpanda-backup.timer
    enabled: true
    state: started
    daemon_reload: true
