---
- name: create envoy gateway namespace
  ansible.builtin.command:
    cmd: kubectl create namespace {{ gateway_namespace }} --dry-run=client -o yaml
  register: ns_manifest
  changed_when: false

- name: apply envoy gateway namespace
  ansible.builtin.command:
    cmd: kubectl apply -f -
    stdin: "{{ ns_manifest.stdout }}"
  changed_when: false

- name: install envoy gateway
  ansible.builtin.command:
    cmd: >-
      helm upgrade --install envoy-gateway oci://docker.io/envoyproxy/gateway-helm
      --version v1.1.2
      --namespace {{ gateway_namespace }}
      --create-namespace
  register: helm_install
  changed_when: "'STATUS: deployed' in helm_install.stdout"
  when: inventory_hostname == groups['k3s_servers'][0]
