name: Linting

on:
  push:
    branches:
      - main
      - feat/*
      - chore/*
  pull_request:

jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
      - name: sync dependencies
        run: uv sync --all-packages
      - name: ruff check
        run: uv run ruff check .
      - name: ruff format check
        run: uv run ruff format --check .
