name: Tests

on:
  push:
    branches:
      - main
      - feat/*
      - chore/*
  pull_request:

jobs:
  test-suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.15.1
      - uses: extractions/setup-just@v2
      - run: just ci-test
