name: Platform Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.15.1
      - name: build check
        run: |
          cd zig && zig build -Doptimize=ReleaseFast
